### ISSUE TITLE
No fixit for `trailing whitespace` not working

### ISSUE THREAD

**Issue by iv-mexx** [Microsoft/vscode-tslint#156]
I've just installed the plugin, and the description states that `trailing whitespace` is among the currently supported quick fixes.

However, it does not work for me - I only get the suggestion to ignore the rule in that place, and it is not fixed when running "Fix all auto-fixable problems"

![screen shot 2016-12-23 at 10 38 19](https://cloud.githubusercontent.com/assets/3407787/21451053/5a8164e4-c8fc-11e6-9124-4bdf836a4978.png)

**Comment by egamma** [comment]
@iv-mexx 

>the description states that `trailing whitespace` is among the currently supported quick fixes.

This description is no longer up to date, sorry. VS Code is now supporting the quick fixes that are provided by tslint 4.0 and a handful of custom fixes provided by the extension directly. I've removed the  the `trailing whitespace` quick fix since the VS Code editor can do this automatically when enabling `"editor.trimAutoWhitespace": true`. 

I've updated the documentation in the README.md.

**Comment by iv-mexx** [comment]
Oh right, did not know about this setting. Thanks 👍

**Comment by thorn0** [comment]
Can we make the extension not show its squiggles for this rule (`no-trailing-whitespace`) when `editor.trimAutoWhitespace` is enabled (directly or via e.g. the EditorConfig extension)?

**Comment by egamma** [comment]
I like this idea since the warning is annoying. Created a separate issue for this #167

**Comment by egamma** [comment]
closing this issue
