### ISSUE TITLE
tslint.autoFixOnSave often goes rogue and adds semi-colons everywhere

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode-tslint#163]
I had `tslint.autoFixOnSave` on and vscode `files.autoSave` set to `onFocusChange` and frequently if I happen to change focus while editing a file with errors -- tslint would go rogue and insert `;` everywhere. It seems it mainly happens when braces are unbalanced.

**Comment by nchen63** [comment]
A precondition to linting is a buildable project (https://palantir.github.io/tslint/usage/cli/), so it sounds like the fixer is being applied in a weird unbuildable state. Having said that, it would be useful if you could reproduce this issue from scratch so that I can see what's going on.

Also, this bug probably belongs in tslint instead of vscode-tslint

**Comment by eamodio** [comment]
@nchen63 It's quite easy to reproduce.

Open `foo.ts` in vscode (with `tslint.autoFixOnSave` set to `true`)
```ts
class Foo {
    bar() {
        return 'baz';
    }

    baz() {
    }
}
```

Edit the file as shown
```ts
class Foo {
    bar() {
        if (true) {
        return 'baz';
    }

    baz() {
    }
}
```

Save the file and it will result in:
```ts
class Foo {
    bar() {
        if (true) {
        return 'baz';
    }

    baz(); { // <-- notice the rogue ;
    }
}
```

While this is a simple case -- it would affect almost every line after the brace unbalance.

**Comment by nchen63** [comment]
yeah, I can repro the issue. It sounds like having both autoSave and autoFixOnSave turned on is sort of a scary combination. Auto fix in tslint was intended to be used with user verification in mind. Auto fix on a non-compilable project _could result in data loss_. I personally would not auto fix without at least seeing a diff before making a separate git commit

**Comment by eamodio** [comment]
IMO the using autoFixOnSave with autoSave on just makes the problem worse, it is still bad even if triggered manually. Since the problem seems to only be triggered by a brace unbalance -- is that something tslint could detect and avoid the semi-colon insertion?

**Comment by abergs** [comment]
We are experiencing problems with this aswell!

**Comment by thorn0** [comment]
Can it probably check that the fixed code is still compilable and revert fixes in case it isn't?

**Comment by nchen63** [comment]
The code isn't compilabe in the first place. That's why it confuses TSLint

**Comment by ryanmcnamara** [comment]
@nchen63 I hit this problem frequently and I do not use autoSave, I only use autoFixOnSave. I will sometimes not notice I have a compilation issue and *manually* save and experience several incorrect autofixes

**Comment by nchen63** [comment]
@ryanmcnamara is your issue the same as @eamodio's? If not, do you have reproducible steps? If they mostly fall under a common set of easy to verify conditions like balanced braces, it may be worth fixing

**Comment by ryanmcnamara** [comment]
@nchen63 It was more or less the same, my issue was with an unclosed paren in tsx, something like
```
const render = () => {
    return (
        <div />
}
```
auto fix yields

```
const render = () => {
    return (
        <div />;
}
```

I doubt that trying to capture all the ways that autofix can fail (and not autofixing when when any of them are true) will be successful. We aren't even sure what all the cases are today, and new autofix rules are being added regularly. As mentioned earlier, tslint has the assumption that you *won't* run autofix unless the code compiles, therefore I think that anything that runs tslint in an automated way should first check that the code compiles.

**Comment by thorn0** [comment]
Another example, I've tried to isolate the issue:
```ts
class A {
	foo() {
		alert(() => {)         // the last closing paren was typed by mistake
			this.bar();
		});
	}
	bar() {

	}
}
```
After save:
```ts
class A {
	foo() {
		alert(() => {);         // the last closing paren was typed by mistake
			this.bar();
		});
	}
	bar(); {    // <==== NB

	}
}
```

**Comment by egamma** [comment]
Triggering autofixing automatically is problematic and for this reason the extension does not invoke autofix when the `autoSave` setting is set to `"files.autoSave": "afterDelay"`. The discussion in this issue illustrates that with tslint it is also too aggressive when the setting is `"files.autoSave": "onFocusChange"`. 

I therefore suggest to always disable autofixing when the save is triggered automatically. The good news is that in 1.10 we have added support to [trigger the save participants](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_10.md#save-participants-trigger) (auto fix is a save participant), when the user presses `CTRL+S` even when the document isn't dirty. This means a user can always explicitly trigger the save participants/auto fixing by pressing `CTRL+S`. Since the user explicitly requested a save, the user should not be surprised by the autofix behaviour.

**Comment by egamma** [comment]
Implemented this proposal https://github.com/Microsoft/vscode-tslint/issues/163#issuecomment-281103558. It works well, a user can always trigger a quick fix by executing a manual save. This also works when the file is already saved.
