### ISSUE TITLE
TSLint is not linting

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-tslint#248]
_From @iamclaytonray on August 30, 2017 0:26_

- VSCode Version: 1.15.1
- OS Version: Mac OS Sierra 10.12.6

Steps to Reproduce:

1. Check out the code <a href="https://stackoverflow.com/questions/45949692/tslint-json-is-not-working-in-vs-code">on SO</a>

I have a completely valid `tslint.json` and `tsconfig.json`. When I run my lint script, `"lint": "tslint ./src/**/*.ts --exclude \"./**/node_modules/**/*.ts\""`, I do get output from my Terminal. But VS Code doesn't highlight or underline any issues. It does not work with or without the extension. I've force-quit several times. I've restarted my computer. I grabbed someone else's tsconfig and tslint from a public repo, with no luck. I even cloned a reputable repo and still get no linting. (<a href="https://github.com/apollographql/apollo-server">apollographql/apollo-server</a>). So, not really knowing what to do, here I am, hopeful to get some help. Thanks!

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#33470_

**Comment by egamma** [comment]
@iamclaytonray what is shown in the output window of tslint when you click the label 'tslint' shown in the status bar when editing a .ts file?

**Comment by iamclaytonray** [comment]
`[Info  - 10:30:54 AM] Linter is running.`

I continued working on getting this back up and running last night. I finally did. I'm honestly not sure what step was the one that fixed the issue but here they are:

- I uninstalled every extension I had. 
- Force quit VS Code
- `npm update -g`
- `npm update -g typescript tslint` (to be extra sure)
- `npm update typescript tslint` (locally)
- Open VS Code again.
- Installed all of my extensions again. (I only have about 15, so it wasn't a big deal to do)
- Reload for extensions.

At some point, I also commented out the `typescript.tsdk` in my settings. I've gotten notices since I installed TypeScript that it wasn't in the right location or something like that. So I just commented it out. I figured that because I have typescript and tslint installed locally as dependencies, that shouldn't affect the extension from behaving correctly. 

And now it works. I have a feeling that it has to do with the tsdk. I've followed solutions from SO before, usually just updating TS but it's never resolved the issue in VS Code.

**Comment by Glavin001** [comment]
@egamma is there a way to see additional debugging info? I also see "Linter is running." when it is not actually working. Thanks in advance!

**Comment by egamma** [comment]
@Glavin001 you can add the setting `"tslint.trace.server": "verbose"` to get additional trace information in the tslint output window.

**Comment by egamma** [comment]
Closing the issue, the original issue was resolved by the reporter.
