### ISSUE TITLE
Autofix for import ignores "semicolon" rule

### ISSUE THREAD

**Issue by Leopotam** [Microsoft/vscode-tslint#266]
tslint.json:
```
"semicolon": [
            true,
            "never"
        ],
```
## Expected  behavior
```
import { IMessage } from "./messages"
```
## Actual behavior
```
import { IMessage } from "./messages";
```
[Example video](https://youtu.be/QX3E4R3pqHM)

**Comment by egamma** [comment]
The autofix for import is provided by the TypeScript language service. TypeScript is unaware of the tslint settings. Nothing the vscode-tslint extension can do about. 

You can file a feature request about the typescript support so that it is configurable whether a semicolon should be inserted by code actions/quick fixes.

**Comment by Leopotam** [comment]
@egamma its not part of typescript service due tslint.json config is part of tslint postprocessor. "semicolon" rule can be autofixed / checked after receiving info from ts lang server on tslint side automatically.

**Comment by egamma** [comment]
You can configure vscode-tslint to autofix on save by enabling the `tslint.autoFixOnSave` setting. 

Automatically fixing tslint rule failures as the user types or the text changes is currently no supported.
