### ISSUE TITLE
Error when TSLint config extends a scoped npm package

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode-tslint#275]
If TSlint extends a scoped package:

```json
{ 
  "extends": ["@scope/package"]
}
```
not that `@scope/package` is extending `tslint-eslint-rules`

Error
```
vscode-tslint: Cannot read tslint configuration - 'Failed to load /path/to/tslint.json: Could not find custom rule directory: /node_modules/tslint-eslint-rules/dist/rules
```

Removing the scoped package from tslint config resolves the issue.

**Comment by emadow** [comment]
thanks @mohsen1 -- also seeing this error.

**Comment by egamma** [comment]
This is caused by the fact that the linter server's home directory is no longer the workspace root. Running at the root folder no longer works when you have a workspace with multiple root-folders.

I would have expected that tslint looks up the scoped package using a `require` call so that the node module resolution is used and the relative path name is not an issue.

@mohsen1 or @emadow can you provide me with a setup so that I can repro the problem?

**Comment by mohsen1** [comment]
I believe our other repo does exactly that! I'll try it and update you. Thanks!

**Comment by egamma** [comment]
@mohsen1  @emadow ping on a repro setup for this issue?

**Comment by egamma** [comment]
Cannot fix without additional information. Please reopen the issue when you can provide more information.

**Comment by egamma** [comment]
Looks like a duplicate of #292, which has been fixed.

**Comment by emadow** [comment]
thanks @egamma
