### ISSUE TITLE
"tslint.alwaysShowRuleFailuresAsWarnings" should be true by default

### ISSUE THREAD

**Issue by ildoc** [Microsoft/vscode-tslint#284]
to avoid confusing linting like this:

![](https://i.imgur.com/ktapx3I.png)

and letting people to enforce syntax checking rules to treat warnings as errors as an option

**Comment by egamma** [comment]
@ildoc 
The severity of warnings can be configured in the tslint.json and these severities should be the default. Overruling the tslint.json configuration should be the exception and therefore it is not on by default.

**Comment by ildoc** [comment]
in the initial scaffolding generated with @angular/cli and create-react-app (with https://github.com/Microsoft/TypeScript-React-Starter), tslint.json has no "defaultSeverity" settings specified, which means that has its default value
but the editor beaviour is the one in the picture posted above

i think default should be green warnings, with no changes neither in tslint.json nor in vscode settings

**Comment by egamma** [comment]
I also prefer that warnings are green by default, but tslint has decided otherwise and the default is error. Tslint allows the user to configure the severities https://palantir.github.io/tslint/usage/configuration/. I suggest to make a PR against the TypeScript-React-Starter with an adjusted tslint.json.

**Comment by ildoc** [comment]
this seems to be the right place where to discussing this issue -> https://github.com/palantir/tslint/issues/2569
