### ISSUE TITLE
Cloned repo but exports are missing in dependencies when trying to develop/debug.

### ISSUE THREAD

**Issue by prograhammer** [Microsoft/vscode-tslint#285]
I've cloned this repo and tried the master branch as well as several tag releases but I'm unable to develop/debug any of them. There seems to be some missing export on some dependency in each release. 

**Reproduce**:
1. Do a fresh git clone.
2. Checkout any tag release. 
3. npm install in `tslint` and `tslint-server`.
4. Open the `tslint` folder and F5 for debug.

**Expected**:
Should open the extension without errors in the new special mode window of vscode.

**What actually happened:**
Window opened, but errors are reported (depending on release). Some exports are missing in dependencies (some labeled "proposal" and so on).

**How do I get a working version for developing on my machine?**

**Comment by prograhammer** [comment]
Looks like I may have fixed it by manually altering the nested dependency versions using a package-lock.json file: `release/1.13`, `vscode-languageclient: 3.4.0`, `vscode-languageserver-protocol: 3.4.0`.

**Comment by prograhammer** [comment]
Is there any way to get newer versions? Looks like it is crashing Vue Language Server (when I open a .vue file).

**Comment by egamma** [comment]
@prograhammer sorry about the hassle, but since the extension is using future API 1.18 and API that is only available in insiders, it is a bit messy.

In your setup steps you miss that after step 3. you have to compile the server once using  `npm run compile`. 

To get the missing API:

- you must develop the extension using vscode-insiders.
- to get latest version of the API, you have to change the engine in the package.json to `^1.18.0` and run npm install again. This will fetch the 1.18 version of vscode.d.ts. I've just committed this change.

I haven't tagged the latest release sorry about that, but it corresponds to what is on master. I'll add a tag after the next publish.

**Comment by prograhammer** [comment]
Oh ok, so sounds like I can just wait for next tagged release and update then. For now I've got it working it seems on 1.13. I'm basically just forking (temporarily while work on [vetur](https://github.com/vuejs/vetur/issues/170) package continues) to allow the extension to lint script tags in `.vue` (single file components) files. Thanks for the awesome open source contribution!

**Comment by egamma** [comment]
I've tagged the latest https://github.com/Microsoft/vscode-tslint/tree/release/1.0.15/tslint. Publishing will have to wait until VS Code 1.18 is out.
