### ISSUE TITLE
"Fix all auto fixable problems" doesn't do anything

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode-tslint#300]
- tslint Version: 1.0.24
- typescript Version: 2.6.2

Open a file with multiple auto fixable problems and run "Fix all auto fixable problems".

Expected: all auto fixable problems should be fixed.
Actual: nothing happens

![screen recording 2017-11-29 at 08 50 am](https://user-images.githubusercontent.com/754768/33387553-721b6f12-d4e2-11e7-925e-6bea5c6435d2.gif)

Reproduces in Visual Studio Code insiders and stable.

**Comment by egamma** [comment]
Tslint 'auto fix all' fixes all tslint errors/warnings. However, the warning you are fixing is not from tslint but from the TypeScript language service/compiler. You can recognize this at the `[ts]` source prefix shown in the error message.

I can understand that this confusing since TypeScript also reports `lint like` warnings. This is currently under discussion here https://github.com/Microsoft/TypeScript/issues/13408#issuecomment-336467493.

I'm closing this issue, since vscode-tslint can do nothing to address it.

**Comment by nicksnyder** [comment]
Ah, thanks for explaining.
