### ISSUE TITLE
Change underline color to avoid confusion with compiler errors

### ISSUE THREAD

**Issue by jhm-ciberman** [Microsoft/vscode-tslint#308]
Hello. I want to ask if it's posible to change the underline color of the linter to avoid confusion with compiler errors. 
Usualy when I am refactoring I am more concerned about compiler errors than linter errors, so it will be a good feature if the default underline color is not red, to be able to recognize linter errors easily from compiler errors. 

Thanks.

**Comment by egamma** [comment]
@jhm-ciberman you have two options to turn linting errors into warnings which are underlined as green and not red:

- configure in your tslint.json that rule failures are shown as warnings by adding `"defaultSeverity": "warning"`
- configure the VS Code setting `tslint.alwaysShowRuleFailuresAsWarnings` so that tslint rule failures are always shown as warnings independent of the configuration in the tslint.json
