### ISSUE TITLE
Supporting rules which require type information

### ISSUE THREAD

**Issue by pelotom** [Microsoft/vscode-tslint#333]
I'm not sure why #70 was closed, given that the problem still persists. The only "workaround" I'm aware of applies only to replacing the `no-unused-variable` rule, and fails to address the fact that there are plenty of other rules I'd like to use which require type information:

```
Warning: The 'deprecation' rule requires type information.
Warning: The 'await-promise' rule requires type information.
Warning: The 'no-floating-promises' rule requires type information.
Warning: The 'no-for-in-array' rule requires type information.
Warning: The 'return-undefined' rule requires type information.
```

It would be really nice if these rules could be supported some day within VSCode!

**Comment by egamma** [comment]
Issue #70 was closed because of this comment https://github.com/Microsoft/vscode-tslint/issues/70#issuecomment-298177554. 

Supporting type information will have to be done in a TypeScript language server plugin and will not be done in this extension. A preview of the TypeScript language server plugin is available, but it isn´t ready yet to replace this extension.
