### ISSUE TITLE
Autofix running wild?

### ISSUE THREAD

**Issue by thepian** [Microsoft/vscode-tslint#369]
- tslint Version: 5.11.0
- typescript Version: 2.9.2

I quite often have automatic changes to imports. This happens without user interaction beyond saving other files.

`import {Logger} from "../../ui";` becomes `import {Logger} from ".."`
`import {} from "@types/googlemaps";` becomes `import "googlemaps"`

Sometimes it affects 100 files, making it super tedious to fix. I can't say what does it. Could it be **vscode-tslint** ?

**Comment by egamma** [comment]
@thepian how do you run the autofix? From the command line or do you have autofixOnSave enabled inside VS Code?

Can you reproduce when you run autofix only from the command line?

Since the autofixed text is not scrambled it looks like this is the result from autofixes applied by tslint.

Notice that in vscode-tslint you can selectively state which tslint diagnostics you want to have autofixed. So as a workaround you could disable the import related diagnostics.

**Comment by egamma** [comment]
@thepian if the changes happen as part of auto import then it isn´t autofix by tslint but auto import by typescript.
For example, it could be this issue https://github.com/Microsoft/TypeScript/issues/23230

**Comment by thepian** [comment]
Sounds likely to be typescript bug. I don't have auto fix enabled on save.

Thanks for the suggestion
