### ISSUE TITLE
tslint.configFile in a multiworkspace root

### ISSUE THREAD

**Issue by dagda1** [Microsoft/vscode-tslint#373]
- tslint Version:5.11.0
- typescript Version: 2.9.1

I have a vscode multi workspace root where a relative path does not make sense as projects are at different levels.

I have tried this:

`"${workspaceRoot}/common/frontend-common/tslint.yaml",`

But it does not pick up the macro.

I can use an absolute path but it would be great if I could just reference the workspace root.

**Comment by egamma** [comment]
@dagda1 can you please provide some more background:
- for what setting would like to refer to the workspaceRoot
- in what configuration files would you like to do so.

**Comment by dagda1** [comment]
@egamma so I have a yarn workspaces project which is a monorepo I have one tslint.yml for all my disparate projects that are at different levels off the root.

I have it in the root of my workspace.

**Comment by egamma** [comment]
@dagda1 still not clear, sorry

In the description you write:

>I have tried this:
>
>`"${workspaceRoot}/common/frontend-common/tslint.yaml",`

Where did you try this, in what file? Was this in the vscode settings file, that is, you tried to set the `tslint.configFile: "${workspaceRoot}/common/frontend-common/tslint.yaml"`?

Since you have the config file in the root of your workspace and you have a mono repo, then tslint should find the config file without any configuration since it searches in ancestor directories, see https://palantir.github.io/tslint/usage/cli/

**Comment by dagda1** [comment]
oh sorry it is not in the root, my apologies, it is in a repo which has java etc.so it is not in the root. That file path is correct

**Comment by egamma** [comment]
Then this looks like feature request https://github.com/Microsoft/vscode/issues/3759 in vscode.

Closing as upstream.
