### ISSUE TITLE
vscode-tslint lints vscode temporary files in problems view

### ISSUE THREAD

**Issue by jhaenchen** [Microsoft/vscode-tslint#380]
- tslint Version: 1.0.34
- typescript Version: 3.0.1

Steps to Reproduce:
I seriously have no idea how this is happening, the files are waaaaay outside the project root.
![image](https://user-images.githubusercontent.com/7771519/43866818-bfdd9fd4-9b2c-11e8-93cf-eca547509ceb.png)

1.?????
2.?????
3.Profit

-------

I was asked to provide more info:

Here is a screenshot of the expanded problems nodes:
![image](https://user-images.githubusercontent.com/7771519/44361730-690e8e00-a484-11e8-9383-9a7b92d04a7a.png)

There are limits on what I can show as this is company code.

As you can see, all of the problems are from tslint trying to find a module and not finding it, presumably because that file is waaaay far away from the necessary node_modules directory. I should mention I do use several other extensions but only one linter.

**Comment by egamma** [comment]
@jhaenchen thanks for following up.

>As you can see, all of the problems are from tslint trying to find a module and not finding it, presumably because that file is waaaay far away from the necessary node_modules directory.

Actually the error messages are not from tslint but from typescript. Tslint error messages have the prefix `tslint` and typescript ones `ts`.

So I suspect this has to do with your typescript configuration in your `tsconfig.json` file. 

I´m closing the issue since it is not tslint specific but CCing @mjbvz whether he has seen such issues in TypeScript.

**Comment by jhaenchen** [comment]
On further examination I think my bug is caused by https://github.com/eamodio/vscode-gitlens/issues/430
