### ISSUE TITLE
Feature: showErrorMessage() when the tslint.json is invalid

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode-tslint#42]
From vscode-eslint:
![image](https://cloud.githubusercontent.com/assets/3254987/14398481/5c6c16f2-fd99-11e5-91ce-9047f1723f2e.png)

A pretty nice feature to have. :rose:

**Comment by egamma** [comment]
The issue was that this error message becomes highly annoying when you have auto save turned on and you are editing the configuration file. 

Here is the flow:
- user edits the tslint.json
- auto save kicks in and saves the tslint.json in the middle of an edit while the file is not syntactically correct
- the tslint linter gets notified that the settings have changed
- tslint validates all open .ts files

The question should at this point an error message be shown? It would be really spamming, since it shows on each auto save. I've decided to now show it and to not validate the code when the tslint configuration is not valid.

For this reason the assumption is that the tslint.json is validated as you edit it using the tslint-json schema.

I think an incorrect tslint.json should not be shown as an error message, but as a status indicator in the status line, then it becomes less annoying and the user understands why no tslinting is taking place.

**Comment by unional** [comment]
That would work too.

But another alternative:
- Do not validate all open .ts files when tslint.json is saved
- Only validate .ts files when they are that active editor

or
- Queue validation until tslint.json is not the active file.

:rose:

**Comment by egamma** [comment]
In 0.5.39 there is a status bar item for tslint that shows an error status indication. The full error message is shown in a 'tslint' output channel.
