### ISSUE TITLE
No handler found for the command: 'tslint.executeAutofix'

### ISSUE THREAD

**Issue by CallMeLaNN** [Microsoft/vscode-tslint#53]
Hi, I got latest VSC 1.2.0 and vscode-tslint 0.5.25 but how to use this autofix?
I checked against #47 and the source code but I'm not really sure about extension development.

I saw `"tslint.enableAutofixOnSave": true` but nothing happened on save and a command `TSLint: Execute Autofix` but VSC complain `No handler found for the command: 'tslint.executeAutofix'. An extension might be missing an activation event.`

**Comment by roman-petrov** [comment]
Juis have installed VSC 1.2 update and updated tslint extension, have exactly the same issue.

**Comment by egamma** [comment]
Good catch. Auto fix on save is currently not supported and is on the backlog. The `Execute Autofix` command is not needed since there is a generic 'Quick Fix' command.

The README now documents how to apply a quick fix and which quick fixes are currently supported. The supported quick fixes are small subset only currently. 

Fixed via b0868b08b90dd78afd7691e68c1350fc24138df6.
